import { Typography, Button } from '@mui/material';
import styled from 'styled-components';
import { useNavigate } from 'react-router-dom';
import { createReviewByChatGPT } from '@/services/article';
import useToast from '@/context/notificationToast/useToast';
import { ToastType } from '@/constants/notification';

const ButtonWrapper = styled.div`
  margin-top: 40px;
`;

interface SideInfoProps {
  gameId?: number;
}
const SideInfo = ({ gameId }: SideInfoProps) => {
  const { setToastIsOpen, setToastContent } = useToast();
  const navigate = useNavigate();

  const handleClick = async () => {
    if (!gameId || gameId < 1) return;
    try {
      await createReviewByChatGPT(gameId);
      setToastContent({
        type: ToastType.SUCCESS,
        message: 'Your review is generated by ChatGPT successfully!',
        duration: 3000,
      });
      setToastIsOpen(true);
      navigate('/reviews');
    } catch (error) {
      setToastContent({
        type: ToastType.ERROR,
        message: "It seems like there's something wrong...",
        duration: 3000,
      });
    }
  };

  return (
    <div>
      <Typography
        component="h4"
        variant="h4"
        sx={{ fontSize: '18px', fontWeight: 700, color: 'gamera.main', marginBottom: '0.2rem' }}
      >
        Writing a Great Post Title
      </Typography>
      <Typography
        component="p"
        variant="body1"
        sx={{ fontSize: '12px', fontWeight: 'normal', color: '#b3b3b3' }}
      >
        Think of your post title as a super short (but compelling!) description — like an overview
        of the actual post in one short sentence. Use keywords where appropriate to help ensure
        people can find your post by search.
      </Typography>
      <ButtonWrapper>
        <Button
          variant="contained"
          component="label"
          sx={{
            marginBottom: 1,
            '&:hover': {
              opacity: 0.8,
            },
          }}
          onClick={handleClick}
        >
          No Idea ? Try ChatGPT !
        </Button>
      </ButtonWrapper>
    </div>
  );
};

export default SideInfo;
